

          spring:
            mail:
              host: smtp.gmail.com
              port: 587
              username: nivodya2001@gmail.com
              password: wupbxphjicpfidgj
              properties:
                mail:
                  smtp:
                    auth: true
                    starttls:
                      enable: true
