import React from 'react';
import yourImage from '../../../assets/report.png'; 

const integrations = [
    {
        title: "Report 01",
        desc: "This was uploaded by Dr. Shantha.",
        icon:   <div className="your-container">
        {/* Replace the SVG code with an img element */}
        <img src={yourImage} alt="Your Icon" className="w-10 h-10" />
      </div>

    },{
        title: "Report 03",
        desc: "This was uploaded by Dr. Ramani.",
        icon:   <div className="your-container">
        {/* Replace the SVG code with an img element */}
        <img src={yourImage} alt="Your Icon" className="w-10 h-10" />
      </div>

    }, {
        title: "Report 03",
        desc: "This was uploaded by Dr. Shantha.",
        icon:   <div className="your-container">
        {/* Replace the SVG code with an img element */}
        <img src={yourImage} alt="Your Icon" className="w-10 h-10" />
      </div>

    },
]

export default () => (
    <section className="py-16">
        <div className="max-w-screen-xl mx-auto px-4 md:px-8">
            <div className="max-w-md">
                <h1 className="text-gray-800 text-xl font-extrabold sm:text-2xl">Reports</h1>
                <p className="text-gray-600 mt-2">
    Access and review the detailed reports generated by your physiotherapists here. These reports provide insights into your progress and treatment plans.
</p>
            </div>
            <ul className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
                {
                    integrations.map((item, idx) => (
                        <li className="border rounded-lg">
                            <div className="flex items-start justify-between p-4">
                                <div className="space-y-2">
                                    {item.icon}
                                    <h4 className="text-gray-800 font-semibold">{item.title}</h4>
                                    <p className="text-gray-600 text-sm">{item.desc}</p>
                                </div>
                                <button className="text-gray-700 text-sm border rounded-lg px-3 py-2 duration-150 hover:bg-gray-100">Connect with doctor</button>
                            </div>
                            <div className="py-5 px-4 border-t text-right">
                                <a href="/prescriptionForm" className="text-indigo-600 hover:text-indigo-500 text-sm font-medium">
                                    View Report
                                </a>
                            </div>
                        </li>
                    ))
                }
            </ul>
        </div>
    </section>
)